services:
  - type: web
    name: oral-cancer-prediction
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      chmod a+x setup.sh
      ./setup.sh
      streamlit run app.py \
        --server.port=$PORT \
        --server.address=0.0.0.0 \
        --server.fileWatcherType none \
        --server.headless=true \
        --server.runOnSave=false \
        --server.enableCORS=false \
        --server.enableXsrfProtection=false \
        --browser.serverAddress=0.0.0.0 \
        --browser.gatherUsageStats=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    plan: free
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /_stcore/health
    healthCheckTimeoutSeconds: 30
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src
