services:
  - type: web
    name: oral-cancer-prediction
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.fileWatcherType none
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
