services:
  - type: web
    name: oral-cancer-prediction
    env: docker
    dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true
    plan: free
