services:
  - type: web
    name: oral-cancer-prediction
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -e .
    startCommand: |
      streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.fileWatcherType none
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: true
    plan: free
